name: solar_term_kit
description: Accurate calculation of 24 solar terms and seasons for Flutter apps. Configurable calculator with time zone support and caching.
version: 0.1.0
homepage: https://github.com/ZenKitX/SolarTermKit
repository: https://github.com/ZenKitX/SolarTermKit
issue_tracker: https://github.com/ZenKitX/SolarTermKit/issues
documentation: https://github.com/ZenKitX/SolarTermKit/blob/main/README.md

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
